version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=058951302734.dkr.ecr.us-east-1.amazonaws.com/aws-cicd-demo-ns
      - echo aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  

