version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn -version

  pre_build:
    commands:
      - echo Pre-build phase started...
      - echo Building JAR...
      - mvn clean package -DskipTests
      - echo Logging in to Amazon ECR...
      - aws --version
      - export REPOSITORY_URI=058951302734.dkr.ecr.us-east-1.amazonaws.com/aws-cicd-demo-ns
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - export DOCKER_CONTAINER_NAME=aws-cicd-demo-ns
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json contents:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/aws-cicd-demo.jar
